// Copyright (c) Microsoft Corporation
// SPDX-License-Identifier: MIT

package io.aura.iaas.policies

import io.aura.core.types.*

/** Fault injection configuration. */
final case class FaultInjectionConfig(
    faultArrivalDistribution: Distribution,
    pesPerFault: Distribution,
    seed: Long = 42L,
    maxFaultTime: Option[SimTime] = None
)

/** Fault event generated by the injection engine. */
final case class HostFault(
    hostId: HostId,
    failedPEs: PEs,
    time: SimTime
)

/** MTBF/MTTR tracking. */
final case class FaultMetrics(
    totalFaults: Int,
    faultsByHost: Map[HostId, Int],
    mtbf: SimTime,
    mttr: SimTime,
    recoveredVms: Int,
    destroyedVms: Int
)

object FaultInjection:
  /** Generate fault events for a set of hosts over the simulation period. */
  def generateFaults(
      hosts: Vector[HostId],
      config: FaultInjectionConfig,
      endTime: SimTime
  ): Vector[HostFault] =
    if hosts.isEmpty then Vector.empty
    else
      val arrivalStream = config.faultArrivalDistribution(config.seed).iterator
      val peStream      = config.pesPerFault(config.seed + 1).iterator
      val hostRng       = new java.util.Random(config.seed + 2)
      val maxTime       = config.maxFaultTime.getOrElse(endTime)
      LazyList
        .unfold(SimTime.Zero) { currentTime =>
          val interArrival = math.abs(arrivalStream.next()) * 3600.0 // hours -> seconds
          val nextTime     = currentTime + SimTime(interArrival)
          if nextTime > maxTime then None
          else
            val hostIdx = hostRng.nextInt(hosts.size)
            val pes     = math.max(1, math.abs(peStream.next()).toInt)
            Some((HostFault(hosts(hostIdx), PEs(pes), nextTime), nextTime))
        }
        .toVector
