// Copyright (c) Microsoft Corporation
// SPDX-License-Identifier: MIT

package io.aura.dsl

import org.apache.pekko.actor.typed.{ActorRef, Behavior}
import org.apache.pekko.actor.typed.scaladsl.{ActorContext, Behaviors}

import io.aura.core.types.*
import io.aura.core.events.*
import io.aura.core.events.SimEventPayload.*
import io.aura.core.engine.TimeCoordinator
import io.aura.core.engine.TimeCoordinator.{EntityCommand, ProcessEvents, StepComplete}

/** Federated broker actor that routes tasks across Edge, Serverless, and K8s tiers.
  *
  * Follows the EdgeBrokerActor pattern:
  *   - Initial FederatedTaskSubmit events are generated by the guardian (spawnEntities)
  *   - Receives paradigm-specific completions/failures via source-based routing
  *   - Applies EscalationPolicy on failure to retry on a different tier
  *   - Emits FederatedTaskCompleted/Failed for metrics collection
  *   - Coordinator terminates on quiescence (event-queue empty + FinalSnapshot handshake)
  */
object FederatedBrokerActor:

  case class TierMapping(
      tier: ExecutionTier,
      targetRef: EntityRef,
      localIdGenerator: () => Long
  )

  case class Config(
      brokerId: String,
      tierSelection: TierSelectionPolicy,
      escalation: EscalationPolicy,
      tierMappings: Map[ExecutionTier, TierMapping],
      coordinator: ActorRef[TimeCoordinator.Command],
      cpuRequired: MIPS,
      memRequired: MegaBytes,
      taskLength: MI,
      deadline: SimTime,
      // Edge-specific config
      edgeSourceNode: String = "",
      // Serverless-specific config
      serverlessFunctionId: FunctionId = FunctionId(0L),
      // K8s-specific config
      k8sDeploymentId: DeploymentId = DeploymentId(0L),
      k8sPodSpec: Option[PodDeploySpec] = None
  )

  case class FederatedTaskState(
      federatedTaskId: FederatedTaskId,
      currentTier: ExecutionTier,
      initialTier: ExecutionTier,
      localId: Long,
      escalations: Int,
      startTime: SimTime,
      remainingTiers: Vector[ExecutionTier]
  )

  case class BrokerState(
      tasks: Map[FederatedTaskId, FederatedTaskState],
      edgeTaskMap: Map[Long, FederatedTaskId],
      invocationMap: Map[Long, FederatedTaskId],
      podMap: Map[Long, FederatedTaskId],
      totalTasks: Int,
      completedTasks: Int,
      failedTasks: Int
  )

  private case class BrokerAccumulator(
      state: BrokerState,
      emittedEvents: Vector[SimEvent]
  )

  /** Generate FederatedTaskSubmit events for all tasks. Called from guardian. */
  def generateEvents(
      brokerRef: EntityRef,
      count: Int,
      startTime: SimTime,
      interArrivalTime: SimTime,
      nextFederatedTaskId: Long,
      cpuRequired: MIPS,
      memRequired: MegaBytes,
      taskLength: MI,
      deadline: SimTime
  ): (Vector[SimEvent], Int) =
    val events = (0 until count).map { i =>
      val taskId      = FederatedTaskId(nextFederatedTaskId + i)
      val arrivalTime = startTime + SimTime(interArrivalTime.value * i)
      SimEvent(
        time = arrivalTime,
        source = brokerRef,
        destination = brokerRef,
        payload = FederatedTaskSubmit(taskId, cpuRequired, memRequired, taskLength, deadline),
        serial = SerialNumber.Zero
      )
    }.toVector
    (events, count)

  def apply(config: Config, totalTasks: Int): Behavior[EntityCommand] =
    Behaviors.setup { context =>
      val entityRef = EntityRef(config.brokerId, EntityType.FederatedBroker)
      config.coordinator ! TimeCoordinator.RegisterEntity(entityRef, context.self)

      val initialState = BrokerState(
        tasks = Map.empty,
        edgeTaskMap = Map.empty,
        invocationMap = Map.empty,
        podMap = Map.empty,
        totalTasks = totalTasks,
        completedTasks = 0,
        failedTasks = 0
      )

      active(config, initialState, entityRef, context)
    }

  private def active(
      config: Config,
      state: BrokerState,
      entityRef: EntityRef,
      context: ActorContext[EntityCommand]
  ): Behavior[EntityCommand] =
    Behaviors.receiveMessage {
      case ProcessEvents(events, replyTo) =>
        val initial = BrokerAccumulator(state, Vector.empty)

        val acc = events.foldLeft(initial) { (acc, event) =>
          event.payload match
            // ─── Self-delivered: initial task submission ───────────
            case FederatedTaskSubmit(taskId, cpuReq, memReq, tLen, dl) =>
              handleFederatedTaskSubmit(acc, event, entityRef, config, taskId, cpuReq, memReq, tLen, dl, context)

            // ─── Edge completions/failures ─────────────────────────
            case EdgeTaskCompleted(edgeTaskId, _, _, _, _, startTime, finishTime, _) =>
              acc.state.edgeTaskMap.get(edgeTaskId.toLong) match
                case Some(fedTaskId) =>
                  handleTierSuccess(acc, entityRef, fedTaskId, finishTime, event.time)
                case None => acc

            case EdgeTaskFailed(edgeTaskId, reason) =>
              acc.state.edgeTaskMap.get(edgeTaskId.toLong) match
                case Some(fedTaskId) =>
                  handleTierFailure(acc, entityRef, config, fedTaskId, reason, event.time, context)
                case None => acc

            case EdgeTaskStarted(_, _, _, _, _, _) =>
              acc // informational

            // ─── Serverless completions/failures ──────────────────
            case InvocationComplete(invId, _, startTime, finishTime, _, _) =>
              acc.state.invocationMap.get(invId.toLong) match
                case Some(fedTaskId) =>
                  handleTierSuccess(acc, entityRef, fedTaskId, finishTime, event.time)
                case None => acc

            case InvocationTimedOut(invId, _, reason) =>
              acc.state.invocationMap.get(invId.toLong) match
                case Some(fedTaskId) =>
                  handleTierFailure(acc, entityRef, config, fedTaskId, reason, event.time, context)
                case None => acc

            case InvocationThrottled(invId, _, reason) =>
              acc.state.invocationMap.get(invId.toLong) match
                case Some(fedTaskId) =>
                  handleTierFailure(acc, entityRef, config, fedTaskId, reason, event.time, context)
                case None => acc

            case InvocationStarted(_, _, _, _) =>
              acc // informational

            // ─── K8s completions/failures ─────────────────────────
            case PodCompleted(podId, _, finishTime) =>
              acc.state.podMap.get(podId.toLong) match
                case Some(fedTaskId) =>
                  handleTierSuccess(acc, entityRef, fedTaskId, finishTime, event.time)
                case None => acc

            case PodFailed(podId, _, reason) =>
              acc.state.podMap.get(podId.toLong) match
                case Some(fedTaskId) =>
                  handleTierFailure(acc, entityRef, config, fedTaskId, reason, event.time, context)
                case None => acc

            case PodUnschedulable(podId, reason) =>
              acc.state.podMap.get(podId.toLong) match
                case Some(fedTaskId) =>
                  handleTierFailure(acc, entityRef, config, fedTaskId, reason, event.time, context)
                case None => acc

            case PodScheduled(_, _, _) | PodStarted(_, _, _) =>
              acc // informational

            case _ =>
              context.log.debug("Federated broker {} ignoring event: {}", config.brokerId, event.payload)
              acc
        }

        if acc.emittedEvents.nonEmpty then config.coordinator ! TimeCoordinator.ScheduleEvents(acc.emittedEvents)

        replyTo ! StepComplete(entityRef)
        active(config, acc.state, entityRef, context)

      case TimeCoordinator.FinalSnapshot(_, replyTo) =>
        // Federated task results are emitted incrementally via
        // `FederatedTaskCompleted` / `FederatedTaskFailed`; no end-of-sim
        // bookkeeping required.
        replyTo ! TimeCoordinator.FinalSnapshotComplete(entityRef)
        Behaviors.same
    }

  private def handleFederatedTaskSubmit(
      acc: BrokerAccumulator,
      event: SimEvent,
      entityRef: EntityRef,
      config: Config,
      taskId: FederatedTaskId,
      cpuRequired: MIPS,
      memRequired: MegaBytes,
      taskLength: MI,
      deadline: SimTime,
      context: ActorContext[EntityCommand]
  ): BrokerAccumulator =
    val availableTiers = config.tierMappings.keys.toVector
    val fedCtx         = FederatedContext(cpuRequired, memRequired, taskLength, deadline, availableTiers)
    val selectedTier   = config.tierSelection(fedCtx)

    routeToTier(
      acc,
      entityRef,
      config,
      taskId,
      selectedTier,
      selectedTier,
      0,
      availableTiers.filterNot(_ == selectedTier),
      event.time,
      context
    )

  private def routeToTier(
      acc: BrokerAccumulator,
      entityRef: EntityRef,
      config: Config,
      taskId: FederatedTaskId,
      targetTier: ExecutionTier,
      initialTier: ExecutionTier,
      escalations: Int,
      remainingTiers: Vector[ExecutionTier],
      currentTime: SimTime,
      context: ActorContext[EntityCommand]
  ): BrokerAccumulator =
    config.tierMappings.get(targetTier) match
      case None =>
        // Tier not available — record failure
        val failEvent = SimEvent(
          time = currentTime,
          source = entityRef,
          destination = EntityRef("sim-guardian", EntityType.SimGuardian),
          payload = FederatedTaskFailed(taskId, s"Tier $targetTier not configured", escalations),
          serial = SerialNumber.Zero
        )
        val updatedState = acc.state.copy(failedTasks = acc.state.failedTasks + 1)
        acc.copy(state = updatedState, emittedEvents = acc.emittedEvents :+ failEvent)

      case Some(mapping) =>
        val localId = mapping.localIdGenerator()
        val (submitEvent, updatedMaps) = targetTier match
          case ExecutionTier.Edge =>
            val edgeTaskId = EdgeTaskId(localId)
            val evt = SimEvent(
              time = currentTime,
              source = entityRef,
              destination = mapping.targetRef,
              payload = EdgeTaskSubmit(
                edgeTaskId,
                config.edgeSourceNode,
                config.cpuRequired,
                config.memRequired,
                config.taskLength,
                config.deadline
              ),
              serial = SerialNumber.Zero
            )
            (evt, acc.state.copy(edgeTaskMap = acc.state.edgeTaskMap + (localId -> taskId)))

          case ExecutionTier.Serverless =>
            val invocationId = InvocationId(localId)
            val evt = SimEvent(
              time = currentTime,
              source = entityRef,
              destination = mapping.targetRef,
              payload = FunctionInvoke(invocationId, config.serverlessFunctionId, config.taskLength, MegaBytes(1.0)),
              serial = SerialNumber.Zero
            )
            (evt, acc.state.copy(invocationMap = acc.state.invocationMap + (localId -> taskId)))

          case ExecutionTier.K8s =>
            val podId = PodId(localId)
            val podSpec = config.k8sPodSpec.getOrElse(
              PodDeploySpec(
                name = s"fed-${taskId.value}",
                namespace = "default",
                containers = Vector(
                  ContainerResourceSpec(
                    "app",
                    "federated:latest",
                    config.cpuRequired,
                    config.cpuRequired,
                    config.memRequired,
                    config.memRequired
                  )
                ),
                restartPolicy = "Never",
                priority = 0,
                nodeSelector = Map.empty
              )
            )
            val evt = SimEvent(
              time = currentTime,
              source = entityRef,
              destination = mapping.targetRef,
              payload = PodScheduleRequest(podId, config.k8sDeploymentId, podSpec),
              serial = SerialNumber.Zero
            )
            (evt, acc.state.copy(podMap = acc.state.podMap + (localId -> taskId)))

        val taskState = FederatedTaskState(
          federatedTaskId = taskId,
          currentTier = targetTier,
          initialTier = initialTier,
          localId = localId,
          escalations = escalations,
          startTime = currentTime,
          remainingTiers = remainingTiers
        )

        context.log.debug("Federated task {} routed to {} (escalation={})", taskId.value, targetTier, escalations)

        val routedEvent = SimEvent(
          time = currentTime,
          source = entityRef,
          destination = entityRef,
          payload = FederatedTaskRouted(taskId, targetTier, escalations + 1),
          serial = SerialNumber.Zero
        )

        acc.copy(
          state = updatedMaps.copy(tasks = updatedMaps.tasks + (taskId -> taskState)),
          emittedEvents = acc.emittedEvents :+ submitEvent :+ routedEvent
        )

  private def handleTierSuccess(
      acc: BrokerAccumulator,
      entityRef: EntityRef,
      fedTaskId: FederatedTaskId,
      finishTime: SimTime,
      currentTime: SimTime
  ): BrokerAccumulator =
    acc.state.tasks.get(fedTaskId) match
      case None => acc
      case Some(taskState) =>
        val completedEvent = SimEvent(
          time = currentTime,
          source = entityRef,
          destination = EntityRef("sim-guardian", EntityType.SimGuardian),
          payload = FederatedTaskCompleted(
            fedTaskId,
            taskState.initialTier,
            taskState.currentTier,
            taskState.escalations,
            taskState.startTime,
            finishTime
          ),
          serial = SerialNumber.Zero
        )
        val updatedState = acc.state.copy(
          completedTasks = acc.state.completedTasks + 1,
          tasks = acc.state.tasks - fedTaskId
        )
        acc.copy(state = updatedState, emittedEvents = acc.emittedEvents :+ completedEvent)

  private def handleTierFailure(
      acc: BrokerAccumulator,
      entityRef: EntityRef,
      config: Config,
      fedTaskId: FederatedTaskId,
      reason: String,
      currentTime: SimTime,
      context: ActorContext[EntityCommand]
  ): BrokerAccumulator =
    acc.state.tasks.get(fedTaskId) match
      case None => acc
      case Some(taskState) =>
        val remaining = taskState.remainingTiers
        config.escalation(taskState.currentTier, reason, remaining) match
          case Some(nextTier) =>
            context.log.debug(
              "Federated task {} escalating from {} to {} (reason: {})",
              fedTaskId.value,
              taskState.currentTier,
              nextTier,
              reason
            )
            // Remove current task state before re-routing
            val cleanedState = acc.state.copy(tasks = acc.state.tasks - fedTaskId)
            val cleanedAcc   = acc.copy(state = cleanedState)
            routeToTier(
              cleanedAcc,
              entityRef,
              config,
              fedTaskId,
              nextTier,
              taskState.initialTier,
              taskState.escalations + 1,
              remaining.filterNot(_ == nextTier),
              currentTime,
              context
            )

          case None =>
            // No more escalation — final failure
            val failEvent = SimEvent(
              time = currentTime,
              source = entityRef,
              destination = EntityRef("sim-guardian", EntityType.SimGuardian),
              payload = FederatedTaskFailed(fedTaskId, reason, taskState.escalations + 1),
              serial = SerialNumber.Zero
            )
            val updatedState = acc.state.copy(
              failedTasks = acc.state.failedTasks + 1,
              tasks = acc.state.tasks - fedTaskId
            )
            acc.copy(state = updatedState, emittedEvents = acc.emittedEvents :+ failEvent)
